### ISSUE TITLE
Voting does sometimes not work properly

### ISSUE THREAD

**Issue by Tokaleto** [notabugio/notabug#9]
I down-voted the comment beginning with "It's only wrong when" in https://notabug.io/t/videos/comments/4e49fcb07adc30625e28bac6ec61ef95aabb6b02/thoughts-did-mama-go-overboard-with-this-a-whoopin-or-nah . When loading this site, at first it displays -1, but then switches to -0. I have tested it on two devices, one of which was used for down-voting the comment.

Also, sometimes a post that has a score bigger than 0 in the listing gets a score of 0 (+0, -0) when you click on it. And if I recall correctly, sometimes your vote does not get accounted in both the listing and the post itself.

**Comment by go1dfish** [comment]
Thanks for the report

Some listing data is cached in the service of performance, there are some issues right now with comment threads requesting data too often and in a way that might lead to the reversal of seen points.

I'll keep this open till that issue is fixed and we'll see if it improves it.

**Comment by go1dfish** [comment]
0.7.0-3 live on notabug.io (what will eventually become 0.7.1) should improve comment data loading behavior and I think will reduce this issue.

It's still normal to vote, see it register, refresh and see it disappear for a bit though; this is the cacheing.

**Comment by go1dfish** [comment]
This should be resolved now.
